insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011', 1, 'TTBox');  
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA', 1, 1, '480676');

--------------------------------------
---- --- -- - Salespoint - -- --- ----
--------------------------------------
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',1, 'Bimp Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',2, 'INACO');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',3, 'DVM');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',4, 'LID SAS');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',5, 'GUILLON');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',6, 'Sogi');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',7, 's2i');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',8, 'Distriprimo');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',9, 'E-vipc.com');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',10, 'mvi');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',11, 'gm-informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',12, 'JLL Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',13, 'WSI');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',14, 'RSI');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',15, 'Class');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',16, 'Informatica 47');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',17, 'sgui');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',18, 'paul-sabatier');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',19, 'EDUC');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',20, 'ADMIN');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',21, 'MAIRIES');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',22, 'UTM');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',23, 'UPS');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',24, 'Automatic 2000');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',25, 'ADMI COMPUTER FRANCE');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',26, 'MANAGER');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',27, 'CAD');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',28, 'nextinfo.fr');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',29, 'STARGONAUT');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',30, 'Altomag');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',31, 'Elio Micro');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',32, 'Tilt Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',33, 'WELCOME informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',34, 'Point Competence Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',35, 'Defis System');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',36, 'cap antigone');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',37, 'Micro Rouen');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',38, 'Micro Sigma');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',39, 'DHS');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',40, 'TKS');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',41, 'Rom');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',42, 'SMD Bureautique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',43, 'MICROTEAM');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',44, 'DATA7');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',45, 'Mac and Co');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',46, 'CID');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',47, 'Isatis');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',48, 'Pixel Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',49, 'Creatis Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',50, 'Micro Systemes');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',51, 'Computer Store TJP Informatique ');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',52, 'ARIS65');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',53, 'Ag Tech');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',54, 'gs2i');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',55, 'CFI Maintenance Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',56, 'Enligne');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',57, 'Pro D Rama');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',58, 'ordilan');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',59, 'mediactive');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',60, 'Artymedia');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',61, 'Asi 52');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',62, 'Cx informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',63, 'ko-network');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',64, 'EUROGRAPH');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',65, 'Goldway France');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',66, 'leclerc');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',67, 'extranetvence');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',68, '3F Systems');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',69, 'Faci');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',70, 'Inter Actif');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',71, 'akantha');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',72, 'MH Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',73, 'ABI France');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',74, 'balistik');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',75, 'REFINFO');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',76, 'NO WORK TECH');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',77, 'Web'in Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',78, 'DPI Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',79, 'AIBS' );
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',80, 'Bestof resellerstore resellerstores');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',81, 'Gips21');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',82, 'Mextor');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',83, 'ECCI');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',84, 'novalto');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',85, 'ISL');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',86, 'opsyre');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',87, 'BDX informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',88, 'Komputer');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',89, 'Adesso Multimedia');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',90, 'EVEN FRANCE');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',91, 'MFVI');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',92, 'login');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',93, 'EURABIS');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',94, 'Micro Plus Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',95, 'AVEROES');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',96, 'districad');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',97, 'APTOR');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',98, 'SLI');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',99, 'JCN Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',100, 'SGEI');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',101, 'PWI Store');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',102, 'jlb formatic');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',103, 'GI Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',104, 'Mafip');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',105, 'ais (arize informatique service)');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',106, 'Pock'it');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',107, 'Active developpement');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',108, 'Store-Media');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',109, 'ais54');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',110, 'site commerciaux');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',111, 'Resellerstore Demo');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',112, 'Acces Resellerstore');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',113, 'techinfo');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',114, 'Click Droit Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',115, 'concepts');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',116, 'INFORMATIQUE.COM');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',117, 'PC 30');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',118, 'Nano Micro');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',119, 'NTS Shop');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',120, 'Adestore');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',121, 'isys');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',122, 'macsi');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',123, 'Les Indispensables');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',124, 'p2m');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',125, 'unidees');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',126, 'periphelie');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',127, 'setf');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',128, 'cds-informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',129, 'urgences micro');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',130, 'dovenco');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',131, 'cdc');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',132, 'Informatique Aquitaine Assistance');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',133, 'mht');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',134, 'fradan');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',135, 'ADNET CONSULTING');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',136, 'DSF Informatique');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',137, 'smvi');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',138, 'PC Partners');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',139, 'IMD INFORMATIQUE');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',140, 'Road Store');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',141, 'discount-micro');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',142, 'isi-groupe');
insert into s_salespoint( version,   version_created_agentid, version_created_date,  version_agentid,  version_date, id , name) values (0, 'init','10-10-2011','init', '10-10-2011',143, 'Hidelog');

commit;



------------------------------------------
---- --- -- - Supplier Price - -- --- ----
------------------------------------------
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',1,1,'475804');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',2,2,'475890');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',3,3,'476065');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',4,4,'476367');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',5,5,'476383');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',6,6,'476392');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',7,7,'476725');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',8,8,'476765');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',9,9,'476843');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',10,10,'476958');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',11,11,'477049');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',12,12,'477118');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',13,13,'477128');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',14,14,'477211');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',15,15,'477258');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',16,16,'477413');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',17,17,'477416');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',18,18,'477717');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',19,19,'477717');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',20,20,'477717');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',21,21,'477717');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',22,22,'477717');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',23,23,'477717');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',24,24,'477717');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',25,25,'477900');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',26,26,'478044');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',27,27,'478135');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',28,28,'478313');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',29,29,'478340');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',30,30,'478479');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',31,31,'478690');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',32,32,'478716');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',33,33,'478772');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',34,34,'478777');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',35,35,'478796');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',36,36,'478949');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',37,37,'478987');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',38,38,'479091');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',39,39,'479328');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',40,40,'479351');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',41,41,'479638');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',42,42,'479676');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',43,43,'480297');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',44,44,'480315');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',45,45,'480481');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',46,46,'480676');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',47,47,'481419');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',48,48,'481444');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',49,49,'481446');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',50,50,'481616');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',51,51,'481951');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',52,52,'482474');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',53,53,'482503');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',54,54,'482550');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',55,55,'482629');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',56,56,'482682');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',57,57,'482749');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',58,58,'482910');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',59,59,'482956');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',60,60,'483101');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',61,61,'483195');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',62,62,'483305');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',63,63,'483489');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',64,64,'483517');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',65,65,'483769');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',66,66,'483769');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',67,67,'483769');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',68,68,'483925');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',69,69,'484007');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',70,70,'484023');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',71,71,'484054');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',72,72,'484103');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',73,73,'484104');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',74,74,'484669');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',75,75,'485043');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',76,76,'485406');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',77,77,'485679');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',78,78,'485856');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',79,79,'485936');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',80,80,'486107');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',81,81,'486120');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',82,82,'486126');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',83,83,'486234');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',84,84,'486291');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',85,85,'486458');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',86,86,'486935');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',87,87,'487210');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',88,88,'487269');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',89,89,'487784');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',90,90,'487910');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',91,91,'488154');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',92,92,'488354');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',93,93,'488453');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',94,94,'488766');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',95,95,'488778');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',96,96,'488981');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',97,97,'489100');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',98,98,'489396');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',99,99,'489618');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',100,100,'489973');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',101,101,'490744');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',102,102,'490900');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',103,103,'491079');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',104,104,'491357');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',105,105,'491492');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',106,106,'491518');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',107,107,'491544');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',108,108,'494886');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',109,109,'496119');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',110,110,'497999');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',111,111,'497999');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',112,112,'497999');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',113,113,'510337');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',114,114,'517001');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',115,115,'520958');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',116,116,'533168');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',117,117,'534208');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',118,118,'534293');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',119,119,'552278');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',120,120,'558131');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',121,121,'558560');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',122,122,'558690');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',123,123,'560205');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',124,124,'564492');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',125,125,'564510');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',126,126,'566432');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',127,127,'572825');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',128,128,'576369');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',129,129,'583652');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',130,130,'584638');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',131,131,'589489');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',132,132,'606879');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',133,133,'608491');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',134,134,'610985');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',135,135,'612077');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',136,136,'612186');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',137,137,'620029');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',138,138,'620087');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',139,139,'623171');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',140,140,'623206');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',141,141,'623271');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',142,142,'624663');
insert into s_salespoint_supplier( version, supplier_type,  id, fk_salespoint, supplier_id) values (  0, 'TECHDATA',143,143,'624825');

commit;


 